config/routes.rb
Rails.application.routes.draw do
  root :to => 'projects#index'

  devise_for :users

  devise_scope :user do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/about', to: 'projects#about', as: 'about'

  resources :projects

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ActiveRecord::Base
  # belongs_to :user

  validates :project_name, :presence => true
  validates :project_technology, :presence => true
  validates :project_description, :presence => true

  has_attached_file :image, styles: { large: "600x600", medium: "300x300>", thumb: "150x150#" }, default_url: "/images/:style/missing.png"
   validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :projects
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #  validates :username, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
      devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :current_password])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "#{@project.project_name} was added!"
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    render :edit
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "#{@project.project_name} was successfully updated!"
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "#{@project.project_name} was successfully deleted."
    redirect_to projects_path
  end

  def about

  end

private
  def project_params
    params.require(:project).permit(:image, :project_name, :project_technology, :project_description)
  end

end

app/controllers/users.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">

  <div class="container">
    <div class="row">
      <p>Hannah Lee | 2018</p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav>
  <p class="logo">HANNAH LEE | Junior Developer</p>
    <li>
      <%= link_to "home", root_path %> &nbsp;
      <%= link_to "about", about_path %> &nbsp;
      <a href="https://github.com/RunHannah/">github</a> &nbsp; <a href="https://linkedin.com/in/hannahlee1">linkedin</a> &nbsp; <a href="https://twitter.com/tweetbyhannah">twitter</a>
    </li>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hannah</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Pavanam" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <p id="flash-notice"><%= flash[:notice] %></p>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= render "layouts/errors", :object => @project %>

<div class="container">
  <br>
  <%= form_for @project, html: { multipart: true } do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <br>
  <%= f.label :project_name %>
  <%= f.text_field :project_name %>
  <br>
  <%= f.label :project_technology %>
  <%= f.text_field :project_technology %>
  <br>
  <%= f.label :project_description %>
  <%= f.text_field :project_description %>
  <br>
  <%= f.submit  %>
  <% end %>
</div>

app/views/projects/about.html.erb
<div class="container">
  <div class="row">
    <div class="col about">
      <p id="about">about: </p>
      <p>Hi there, this site is currently being updated as I complete my education on the Ruby/Rails track at Epicodus. As a career changer from public sector budget and policy analysis to developer, I can't wait to apply my skills to solve meaningful problems and encourage others who may be interested in coding, but intimidated by it, to try it out.</p>
      <p>I bring an eye for detail, critical thinking, and perseverance to find the right solution. I have been learning the following technologies and am actively pursuing professional opportunities that encourage learning and value diversity and inclusion.</p>
    </div>
    <div class="col technologies">
      <p>Technologies</p>
      <ul>
        <li>Languages: JavaScript, Ruby</li>
        <li>Frameworks: Angular 5, Rails </li>
        <li>Database:  PostgreSQL, Firebase</li>
        <li>Testing:  Jasmine, Karma, RSpec</li>
        <li>Styling: Bootstrap, Materialize</li>
        <li>Other:  NodeJS, Git, Github, Postman, AJAX, HTML, CSS</li>
      </ul>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <h1>Edit Project</h1>

  <% if current_user && current_user.admin %>
    <%= render "form" %>
  <% end %>
</div>

app/views/projects/index.html.erb
<div class="container" id="projects">

  <% if current_user && current_user.admin %>
    <a><%= link_to "Add a Project", new_project_path %></a>
  <% end %>

  <div class="section">
    <div class="row">
      <% @projects.each do |project| %>
      <div class="col m6 m6">
        <div class="card">
          <div class="card-image">
            <img class="activator" src="<%= project.image.url(:medium) %>">
          </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">
              <!-- <i class="material-icons right">more_vert</i></span> -->
              <p><%= link_to project.project_name, project_path(project) %></p>
              <p><a href="<%= project.deployed %>">Live</a></p>
              <p>Technologies Used: </p><%= project.project_technology %>
              <br>
              <p>Description: </p><%= project.project_description %>
            </div>

              <!-- <div class="card-reveal">
              <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
              <p>Here is some more information about this product that is only revealed once clicked on.</p>
            </div> -->

        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <h4>Enter New Project Details</h4> 

  <%= render "form" %>
</div>

app/views/projects/resume.html.erb
<h1>Hello World</h1>

app/views/projects/show.html.erb
<div class="container">
  <p id="project-title"><%= @project.project_name %></p>
  <% if current_user && current_user.admin %>
    <a><%= link_to "Edit This Project", edit_project_path(@project) %></a>
  <% end %>

  <div class="card" id="project-show">
    <div class="card-body">
      <li style="list-style:none;">

        <%= image_tag @project.image.url(:large) %>

        <br>
        <strong>Technologies Used: </strong><%= @project.project_technology %>
        <br>
        <strong>Description: </strong><%= @project.project_description %>
        <br>
        <a href="<%= @project.github %>">Github</a>

      </li>
    </div>
  </div>
</div>